---
abstract: "Harness output delegate for Atlassian's Bamboo CI server"
author:
  - 'Piotr Piątkowski <pp@idea7.pl>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TAP-Formatter-Bamboo
provides:
  TAP::Formatter::Bamboo:
    file: lib/TAP/Formatter/Bamboo.pm
    version: 0.02
  TAP::Formatter::Bamboo::Session:
    file: lib/TAP/Formatter/Bamboo/Session.pm
    version: 0
requires:
  Encode: 2.42
  Moose: 2
  MooseX::NonMoose: 0.2
  TAP::Harness: 3.2
  XML::LibXML: 2
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
